# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
install:
- cd Example
- pod install
script:
- xctool test -workspace Example/MUKUserNotificationViewController.xcworkspace -scheme MUKUserNotificationViewController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
